server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=Content-Type, application/json
            - JwtAuthenticationFilter

        - id: HOTELSERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/hotels/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=Content-Type, application/json
            - JwtAuthenticationFilter

        - id: RATINGSERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/ratings/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=Content-Type, application/json
            - JwtAuthenticationFilter

eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

# JWT Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 24 hours in milliseconds
